stages:
  - deploy

deploy_flask_prometheus_grafana:
  image: docker:stable
  services:
    - docker:dind
  stage: deploy
  script:
    # Step 1: Clone the Flask app repository
    - git clone https://github.com/hassan90122/simple-flask-app.git ~/simple-flask-app
    - cd ~/simple-flask-app

    # Step 2: Remove any existing containers and images
    - docker stop flask-app || true
    - docker rm flask-app || true
    - docker rmi flask-app || true

    - docker stop prometheus || true
    - docker rm prometheus || true
    - docker rmi prom/prometheus || true

    - docker stop grafana || true
    - docker rm grafana || true
    - docker rmi grafana/grafana-oss || true

    # Step 3: Build and run Flask app container
    - docker build -t flask-app .
    - docker run -d --name flask-app -p 5000:5000 flask-app

    # Step 4: Create Prometheus config file
    - echo "
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'flask-app'
          static_configs:
            - targets: ['localhost:5000']
      " > ~/prometheus.yml

    # Step 5: Run Prometheus container
    - docker run -d --name prometheus -p 9090:9090 -v ~/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

    # Step 6: Run Grafana container
    - docker run -d --name=grafana -p 3000:3000 grafana/grafana-oss
