version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a Python Docker image
    steps:
      - checkout  # Check out the code from the repository

      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - run:
          name: Stop existing containers
          command: |
            docker stop flask-app || true
            docker rm flask-app || true
            docker stop prometheus || true
            docker rm prometheus || true
            docker stop grafana || true
            docker rm grafana || true

      - run:
          name: Remove existing Docker images
          command: |
            docker rmi flask-app || true
            docker rmi prom/prometheus || true
            docker rmi grafana/grafana-oss || true

      - run:
          name: Build Docker image for Flask app
          command: |
            docker build -t flask-app .

      - run:
          name: Run Flask app container
          command: |
            docker run -d --name flask-app -p 5000:5000 flask-app

      - run:
          name: Create Prometheus config file
          command: |
            echo "global:
              scrape_interval: 15s
            scrape_configs:
              - job_name: 'flask-app'
                static_configs:
                  - targets: ['localhost:5000']" > prometheus.yml

      - run:
          name: Run Prometheus container
          command: |
            docker run -d --name prometheus -p 9090:9090 -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

      - run:
          name: Run Grafana container
          command: |
            docker run -d --name=grafana -p 3000:3000 grafana/grafana-oss

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
