name: Deploy Flask App with Prometheus and Grafana

on:
  workflow_dispatch:   # Allows manual triggering of the workflow
  push:
    branches:
      - main          # Runs on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to stop and remove existing containers and images
      - name: Clean up existing containers and images
        run: |
          docker stop flask-app || true
          docker rm flask-app || true
          docker rmi flask-app || true
          docker stop prometheus || true
          docker rm prometheus || true
          docker rmi prom/prometheus || true
          docker stop grafana || true
          docker rm grafana || true
          docker rmi grafana/grafana-oss || true

      # Step to build Flask app image
      - name: Build Flask app image
        run: |
          docker build -t flask-app .

      # Step to run Flask app container
      - name: Run Flask app container
        run: |
          docker run -d --name flask-app -p 5000:5000 flask-app

      # Step to create Prometheus config file
      - name: Create Prometheus config
        run: |
          echo "global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'flask-app'
              static_configs:
                - targets: ['localhost:5000']" > prometheus.yml

      # Step to run Prometheus container
      - name: Run Prometheus container
        run: |
          docker run -d --name prometheus -p 9090:9090 -v $(pwd)/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

      # Step to run Grafana container
      - name: Run Grafana container
        run: |
          docker run -d --name=grafana -p 3000:3000 grafana/grafana-oss
